### PR TITLE
Lecture/lec23

### PR DESCRIPTION
**Pull request by danhammer**
Final lecture notes for the Nov 10 class (Lecture 22).  They're not perfect, but it's pretty good, I think!  The Google Slides will be posted separately.

### CODE REVIEW

**Comment by danhammer** [comment]
Note that I renamed the branch  to correspond to Lecture 23  rather than Lecture 22.  I got the number wrong.  But we're good now!  No merge conflicts.

**Comment by fperez** [comment]
Awesome, thanks so much @danhammer !! Looking forward to seeing this in action tomorrow :)

**Comment by danhammer** [comment]
Thanks @fperez, I am still finishing the slides, but [here is the link](https://docs.google.com/presentation/d/1btHl4qCIZDCOfil3cNYZEyioH_iUk52ee1JsBd0ahjg/edit?usp=sharing) for now.  I will add them into the master deck as soon as possible.

**Comment by fperez** [comment]
Thanks @danhammer for the fabulous lecture and your materials!

We'll link to your slides, but it would be awesome if you can add them to the main deck so we have an archival copy for the course (I can't do it as with view-only permissions I can't copy/download - if you give me edit rights for a minute I can do it for you too).

**Pull request merged**
